---
kind: pipeline
type: docker
name: a

platform:
  arch: amd64
  os: linux

steps:
- name: hello-worlda
  image: docker/whalesay
  commands:
  - cowsay this is a

- name: hello-worldaaaaaaaaaaaaa
  image: docker/whalesay
  commands:
  - cowsay $DRONE_JOB_STATUS

---
kind: pipeline
type: docker
name: b

platform:
  arch: amd64
  os: linux

steps:
- name: hello-worldb
  image: docker/whalesay
  commands:
  - cowsay fail

- name: hello-worldbaaaaaa
  image: docker/whalesay
  commands:
  - exit 1

- name: hello-worldaaaaaaaaaaaaa
  image: docker/whalesay
  commands:
  - cowsay $DRONE_JOB_STATUS
  when:
    status:
    - success
    - failure

---
kind: pipeline
type: docker
name: C

platform:
  arch: amd64
  os: linux

steps:
- name: hello-worldaaaaaavv
  image: docker/whalesay
  commands:
  - cowsay this is c

- name: hello-worldaaavvfffffffffffffaaaaaaaaaa
  image: docker/whalesay
  commands:
  - cowsay $DRONE_JOB_STATUS